spring:
  application:
    name: picwave-backend
  # 最大文件体积配置
  servlet:
    multipart:
      max-file-size: 10MB
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/picwave
    username: root
    password: root
  # Redis配置
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 5000
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 200
        # 连接池最大空闲连接数
        max-idle: 10
        # 连接池最小空闲连接数
        min-idle: 0
        # 连接池最大等待时间
        max-wait: -1ms
  # Session配置
  session:
    store-type: redis
# 服务器配置
server:
  port: 8123
  servlet:
    context-path: /api
    # Cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
        domain: picwave.com
# Mybatis-Plus 配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    # 仅在开发环境开启日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
# 接口文档配置
knife4j:
  enable: true
  openapi:
    title: "接口文档"
    version: 1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.eureka.picwavebackend.controller